apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: my-app-name
  replicas: 3
  template:
    metadata:
      name: my-app-name
      labels:
        app: my-app-name
    spec:
      containers:
        - name: my-nginx-app
          image: os_project
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "100Mi"